// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    Choice: typeof import('./src/components/Choice.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
  }
}

export {}
